# SITE MAPPING
site_mapping = {
  "walmart-az-buckeye-site1": "BCK",
  "walmart-fl-brooksville-site25": "BRK", 
  "walmart-ga-douglas-site1": "DOUG",
  "walmart-ms-brookhaven-site1": "BRH",
  "walmart-oh-grovecity-site1": "GRC",
  "walmart-or-hermiston-site1": "HRM",
  "walmart-tn-midway-site1": "MID",
  "walmart-tx-newbraunfels-site1": "NBF",
  "walmart-tx-palestine-site1": "PAL",
  "walmart-wi-menomonie-site1": "MNM",
  "walmart-ny-marcy-site1": "MRC",
  "walmart-nh-raymond-site1": "RYM",
  "walmart-nc-hopemills-site1": "HPM",
  "walmart-ks-ottawa-site1": "OTW",
  "walmart-pa-woodland-site1": "WDL",
  "walmart-al-cullman-site1": "CLM",
  "walmart-in-seymour-site1": "SYM",
  "walmart-tx-plainview-site1": "PLV",
  "walmart-ar-searcy-site1": "SRC",
  "walmart-va-sutherland-site1": "LVL",
  "walmart-ca-redbluff-site1": "RBL"
} 

# SITE TIMEZONE MAPPING
site_timezone_mapping = {
  "site_timezones": {
    "NBF": "America/Chicago",
    "BCK": "America/Phoenix",
    "BRK": "America/Chicago", 
    "BRH": "America/Chicago",
    "CLM": "America/Chicago",
    "DOUG": "America/Chicago",
    "GRC": "America/Chicago",
    "HPM": "America/Chicago",
    "HRM": "America/Chicago",
    "MID": "America/Chicago",
    "MNM": "America/Chicago",
    "MRC": "America/Chicago",
    "OTW": "America/Chicago",
    "PAL": "America/Chicago",
    "RYM": "America/Chicago",
    "WDL": "America/New_York",

    "afs-ut-farrwest-site1": "America/Denver",
    "albertsons-ca-irvine-site1": "America/Los_Angeles",
    "cns-ct-windsorlocks-site1": "America/New_York",
    "unfi-pa-manchester-site1": "America/New_York",
    "unfi-wa-centralia-site1": "America/Los_Angeles",
    "walmart-al-cullman-site1": "America/Chicago",
    "walmart-ar-searcy-site1": "America/Chicago",
    "walmart-az-buckeye-site1": "America/Phoenix",
    "walmart-ca-porterville-site1": "America/Los_Angeles",
    "walmart-ca-redbluff-site1": "America/Los_Angeles",
    "walmart-co-loveland-site1": "America/Denver",
    "walmart-fl-brooksville-site25": "America/New_York",
    "walmart-ga-douglas-site1": "America/New_York",
    "walmart-in-seymour-site1": "America/New_York",
    "walmart-ks-ottawa-site1": "America/Chicago",
    "walmart-ms-brookhaven-site1": "America/Chicago",
    "walmart-nc-hopemills-site1": "America/New_York",
    "walmart-nh-raymond-site1": "America/New_York",
    "walmart-ny-marcy-site1": "America/New_York",
    "walmart-oh-grovecity-site1": "America/New_York",
    "walmart-or-hermiston-site1": "America/Los_Angeles",
    "walmart-pa-woodland-site1": "America/New_York",
    "walmart-tn-midway-site1": "America/Chicago",
    "walmart-tx-newbraunfels-site1": "America/Chicago",
    "walmart-tx-palestine-site1": "America/Chicago",
    "walmart-tx-plainview-site1": "America/Chicago",
    "walmart-va-sutherland-site1": "America/New_York",
    "walmart-wi-menomonie-site1": "America/Chicago"
  },
}